pipelines:
  default:
    - step:
        name: Sync to GitHub
        script:
          - git config --global user.email "medevkenya@gmail.com"
          - git config --global user.name "medevkenya"
          - git remote add github https://gitlab.com/medevkenya/harperbarzar.git
          - git push github --all
